[project]
name = "prediction-market"
description = "Stacks Prediction Market - Binary Options on BTC Price"
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.prediction-market]
path = "contracts/prediction-market.clar"
clarity_version = 2
epoch = 2.5

[contracts.prediction-market-v2]
path = "contracts/prediction-market-v2.clar"
clarity_version = 2
epoch = 2.5

[contracts.mock-usdcx]
path = "contracts/mock-usdcx.clar"
clarity_version = 2
epoch = 2.5

[contracts.prediction-pools]
path = "contracts/prediction-pools.clar"
clarity_version = 2
epoch = 2.5
