[network]
name = "simnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
balance = 10_000_000_000_000

[accounts.wallet_1]
mnemonic = "letter advice cage absurd amount doctor acoustic avoid letter advice cage above"
balance = 10_000_000_000_000

[accounts.wallet_2]
mnemonic = "jelly better achieve collect unaware mountain thought cargo oxygen act hood bridge"
balance = 10_000_000_000_000

[accounts.wallet_3]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
balance = 10_000_000_000_000
